name: clashforge_mobile
description: "ClashForge Mobile VPN Client"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  yaml: ^3.1.2
  http: ^1.1.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/geodata/country.mmdb
    - assets/geodata/geosite.dat
    - assets/mihomo/arm64-v8a
    - assets/mihomo/armeabi-v7a
    - assets/mihomo/x86_64
